### ISSUE TITLE
mysql-python fails importing ConfigParser during 'pip install mysql-python'.

### ISSUE THREAD

**Issue by bubthegreat** [PureStorage-OpenConnect/FlashStache#2]
Error during install installing mysql-python during setup.sh run:

```
Collecting MySQL-python
  Downloading MySQL-python-1.2.5.zip (108kB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-xebzdk8g/MySQL-python/setup.py", line 13, in <module>
        from setup_posix import get_config
      File "/tmp/pip-build-xebzdk8g/MySQL-python/setup_posix.py", line 2, in <module>
        from ConfigParser import SafeConfigParser
    ImportError: No module named 'ConfigParser'
```

Repro happens any time we execute:
```
micheal.taylor@bubdev:~/FlashStache$ sudo -H pip install mysql-python
Collecting mysql-python
  Downloading MySQL-python-1.2.5.zip (108kB)
    100% |████████████████████████████████| 112kB 1.2MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-1lrjony6/mysql-python/setup.py", line 13, in <module>
        from setup_posix import get_config
      File "/tmp/pip-build-1lrjony6/mysql-python/setup_posix.py", line 2, in <module>
        from ConfigParser import SafeConfigParser
    ImportError: No module named 'ConfigParser'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-1lrjony6/mysql-python/
```

**Comment by bubthegreat** [comment]
Duplicate of more explicit bug #4
